#spring:
#  application:
#    name: discovery-service
#server.port: 8761
#eureka:
#  instance:
#    preferIpAddress: true
#  renewalPercentThreshold: 0.85
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
