server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassname: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: test123
